# Generated by Django 6.0.3 on 2026-03-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('BR', 'Brasil'), ('UK', 'Reino Unido'), ('FR', 'França'), ('DE', 'Alemanha'), ('IT', 'Itália'), ('JP', 'Japão'), ('IN', 'Índia'), ('CN', 'China'), ('ES', 'Espanha')], max_length=100, null=True)),
            ],
        ),
    ]
